"""Pre-cached narration loader (D-NARRATOR-11).

Loads ``cache/narrations/{slug}.json`` containing
``Verdict.model_dump_json(indent=2)`` output. Cached narrations are
regenerated by ``scripts/regenerate_cache.py`` (templated bootstrap or
Anthropic Haiku 4.5 via the workflow_dispatch GHA per D-NARRATOR-09).

The cache is the demo's economic model: zero per-visitor Anthropic API
spend (D-NARRATOR-05 + Pitfall 10 mitigation). Synthetic-tab card clicks
load these JSONs instead of calling the LLM at request time.

Stale-cache safety: ``tests/test_narrations_cache.py`` runs on every PR
(D-NARRATOR-12) and hard-fails CI (D-NARRATOR-06) if any cached citation
breaks against regenerated telemetry, or if the cached top_class drifts
from the live classifier output (Pitfall E mitigation).
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from wifi_diag_schema.verdict import Verdict

_CACHE_DIR = Path(__file__).parent.parent.parent / "cache" / "narrations"


@lru_cache(maxsize=8)  # 8 scenarios fit in memory comfortably
def load_cached_narration(slug: str) -> Verdict:
    """Load a pre-generated narration; raises FileNotFoundError if missing.

    Args:
        slug: Scenario slug (must be a key in
            ``src.space.scenarios.catalog.SCENARIOS_BY_SLUG``).

    Returns:
        A Verdict deserialized from ``cache/narrations/{slug}.json``.

    Raises:
        FileNotFoundError: If the cache file is missing -- caller should
            fall back to ``narrate_templated`` (defense in depth).
    """
    path = _CACHE_DIR / f"{slug}.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing cached narration for {slug!r}. "
            f"Run `make cache-narrations` (or `make cache-narrations-templated` "
            f"without an Anthropic API key) to regenerate."
        )
    return Verdict.model_validate_json(path.read_text(encoding="utf-8"))
